### ISSUE TITLE
Added Code Snippets for Javascript

### ISSUE THREAD

**Issue by namuan** [namuan/dev-rider#4]
Add code snippets for existing tools in Javascript language. See https://github.com/namuan/dev-rider-codesnippets

**Comment by abhijit-hota** [comment]
Hello.
I'd like to work on this issue. Can you guide me?

**Comment by namuan** [comment]
Hi,
Please checkout the code snippets repo here - https://github.com/namuan/dev-rider-codesnippets and follow the README file there to add code snippets for Javascript. 

Let me know if anything is confusing or if you are stuck anywhere.

thanks

**Comment by abhijit-hota** [comment]
> Hi,
> Please checkout the code snippets repo here - https://github.com/namuan/dev-rider-codesnippets and follow the README file there to add code snippets for Javascript.
> 
> Let me know if anything is confusing or if you are stuck anywhere.
> 
> thanks

Thank you!
